/* Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
var fibonacci = function(){
  var fibAr = [1,2];
  var ttlSum = 0;
  while (fibAr[fibAr.length-1] < 4000000) {
    fibAr.push(fibAr[fibAr.length-1] + fibAr[fibAr.length-2]);
  }
  for (i = 1; i < fibAr.length-1; i++) {
    if (fibAr[i] % 2 == 0) {
      ttlSum += fibAr[i];
    }
  }
  return ttlSum;
}

console.log(fibonacci());
